# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

maven_group = com.getItemFromBlock.create_tweaked_controllers
name = create_tweaked_controllers
archives_base_name = create_tweaked_controllers
version = 1.18.2-1.2.4

description = A Create Addon that adds a way of controlling contraptions using an advanced controller. Compatible with Create 0.5.1+

minecraft_version = 1.18.2
minecraft_range = [1.18.2,1.19) 
# what this is ^

architectury_version = 4.11.93
enabled_platforms=fabric,forge

# Fabric
fabric_loader_version = 0.15.7
fabric_api_version = 0.77.0+1.18.2

# Forge
forge_version = 40.2.17
loader_range = [40,)
forge_range = [40.2.17,)

create_fabric_version = 0.5.1-f-build.1415
create_forge_version = 0.5.1.f-332

flywheel_version = 0.6.9-101
registrate_version = MC1.18.2-1.1.3

create_range = [0.5.1.a,)

jei_version = 9.7.0.209
emi_version = 0.7.3

cc_restitched_version = 1.100.8
cc_tweaked_version = 1.101.3

controllable_version = 4376751

mixingradle_version = 0.7-SNAPSHOT
mixin_version = 0.8.5

# GitHub information
github_project = getItemFromBlock/Create-Tweaked-Controllers