# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs = -Xmx3G
org.gradle.daemon = false

maven_group = com.getItemFromBlock.create_tweaked_controllers
name = Create: Tweaked Controllers
archives_base_name = create_tweaked_controllers
mod_id = create_tweaked_controllers
version = 1.2.4
authors = getItemFromBlock

description = A Create Addon that adds a way of controlling contraptions using an advanced controller

minecraft_version = 1.18.2
minecraft_range = [1.18.2,1.19)

architectury_version = 4.11.93
enabled_platforms = fabric,forge

shadow_plugin_version = 7.1.2

# Fabric
fabric_loader_version = 0.15.7
fabric_api_version = 0.77.0+1.18.2

# Forge
forge_version = 40.2.17
forge_range = [40,)

create_fabric_version = 0.5.1-f-build.1415
create_forge_version = 0.5.1.f-332

flywheel_version_forge = 0.6.10-105
flywheel_version_fabric = 0.6.10-39
registrate_version = MC1.18.2-1.1.3

create_range = [0.5.1.a,)

jei_version = 10.2.1.283
emi_version = 0.7.3

cc_restitched_version = 1.100.8
cc_tweaked_version = 1.101.3

controllable_version = 4376751

mixingradle_version = 0.7-SNAPSHOT
mixin_version = 0.8.5

# GitHub information
github_project = getItemFromBlock/Create-Tweaked-Controllers