modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
issueTrackerURL = "https://github.com/getItemFromBlock/Create-Tweaked-Controllers/issues"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL = "https://github.com/getItemFromBlock/Create-Tweaked-Controllers"
logoFile = "../resources/logo.png"
authors = "getItemFromBlock"
description = '''
A Create Addon that adds a way of controlling contraptions using an advanced controller.
Compatible with Create 6.0.0+
'''

[[mixins]]
config = "${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "create"
type = "required"
versionRange = "[6.0.0,)"
ordering = "NONE"
side = "BOTH"
